# Generated by Django 3.1 on 2021-01-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_product_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
    ]
