# Generated by Django 3.1 on 2021-01-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_product_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accum_volume',
            field=models.CharField(default='', max_length=255, verbose_name='Battery'),
        ),
        migrations.AddField(
            model_name='product',
            name='diagonal',
            field=models.CharField(default='', max_length=255, verbose_name='Diagonal'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_type',
            field=models.CharField(default='', max_length=255, verbose_name='Display type'),
        ),
        migrations.AddField(
            model_name='product',
            name='frontal_cam',
            field=models.CharField(default='', max_length=255, verbose_name='Selfie camera'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_cam',
            field=models.CharField(default='', max_length=255, verbose_name='Main camera'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(default='', max_length=255, verbose_name='RAM'),
        ),
        migrations.AddField(
            model_name='product',
            name='resolution',
            field=models.CharField(default='', max_length=255, verbose_name='resolution'),
        ),
    ]
